name: Deploy Theme

defaults:
  run:
    working-directory: .

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose an environment to deploy to:"
        type: environment
        required: true
        default: "UAT"

jobs:
  build:
    if: "! contains(github.event.head_commit.message, 'skip-ci') && ! contains(github.event.head_commit.message, 'infra')"
    name: Build and Test
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    strategy:
      matrix:
        node-version: [16]
    steps:
      - uses: actions/checkout@v3
      - name: Authenticate with private NPM package
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test --if-present
      - run: yarn install
      - run: yarn build-prod
      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: ${{ vars.SLACK_BUILD_CHANNEL_ID }}'
          slack-message: "Build Started: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

  deploy:
    name: Deploy to Shopify (UAT)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: GitHub Refs
        uses: rlespinasse/github-slug-action@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler: latest

      - name: Install Shopify CLI
        run: npm install -g @shopify/cli @shopify/theme

      - name: Update Theme
        if: github.event.action == 'synchronize'
        run: shopify theme push --path ./ --theme git-${{ env.GITHUB_HEAD_REF_SLUG_URL }}

      - name: Create Theme
        if: github.event.action == 'opened' || github.event.action == 'reopened'
        run: shopify theme push --path ./ --theme git-${{ env.GITHUB_HEAD_REF_SLUG_URL }} --unpublished

      - name: Delete Theme
        if: github.event.action == 'closed'
        run: shopify theme delete --theme git-${{ env.GITHUB_HEAD_REF_SLUG_URL }}

      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: ${{ vars.SLACK_BUILD_CHANNEL_ID }}'
          slack-message: "Build Complete: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
